DROP PROCEDURE stddev@

CREATE PROCEDURE stddev(OUT RESULT dec(15, 10))
	LANGUAGE SQL
	BEGIN
		DECLARE SQLSTATE CHAR(5) DEFAULT '00000';
		DECLARE SALARY double;
		DECLARE SUM_SALARY double;
		DECLARE SUM_SALARY_SQUARE double;
		DECLARE COUNT int;
		DECLARE cursor CURSOR FOR SELECT SALARY FROM EMPLOYEE;
			SET SUM_SALARY = 0;
			SET SUM_SALARY_SQUARE = 0;
			SET COUNT = 0;
			OPEN cursor;
			FETCH FROM cursor INTO SALARY;
			WHILE(SQLSTATE='00000') DO
				SET SUM_SALARY = SUM_SALARY + SALARY;
				SET SUM_SALARY_SQUARE = SUM_SALARY_SQUARE + SALARY*SALARY;
				SET COUNT = COUNT + 1;
				FETCH FROM cursor INTO SALARY;
			END WHILE;
			CLOSE cursor;
			SET RESULT = SQRT(SUM_SALARY_SQUARE/COUNT - (SUM_SALARY/COUNT)*(SUM_SALARY/COUNT));
	END@ 

	CALL stddev(?)@